# -*- coding: utf-8 -*-
"""API Candidaturas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157BSGaN2m9edM8au8HRafcOdgs8YjM2n
"""

############################################################
# Script para consumir los datos de la API Candidaturas
# https://www.apielectoral.mx
# Guarda los CSV resultantes en Google Drive
# Limpia los datos de la variable 'name'
#
# To do:
# Revisar otras columnas  por datos que se puedan limpiar
#
#############################################################

# Importa y configura el Google Drive
from google.colab import drive
drive.mount('/content/drive')

import json, requests, sys
import pandas as pd
import csv

url ='https://e7f1hlosbh.execute-api.us-east-2.amazonaws.com/staging/export-officeholders'

response = requests.get(url)

c = json.loads(response.content)

c.keys()

# Extrae los datos que vienen en diccionarios y los asigna a su fila

for key in c.keys():
  print(key) 
  df = pd.DataFrame(c[key])
  if key != 'other-names':
    if 'name' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'name'][i]= df.name[i]['en_US']

    if 'abbreviation' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'abbreviation'][i]= df.abbreviation[i]['en_US']

    if 'title' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'title'][i]= df.title[i]['en_US']
 
    if 'first_name' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'first_name'][i]= df.first_name[i]['en_US']

    if 'last_name' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'last_name'][i]= df.last_name[i]['en_US']

    if 'full_name' in df.columns : 
      
      for i in range(len(df)):  
             
        df.loc[: , 'full_name'][i]= df.full_name[i]['en_US']
  
  path = 'drive/MyDrive/candidatos/' + key + '.csv'
  df.to_csv(path, index=False)
